services:
  app:
    container_name: pipimink-app
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - pipimink-network
    command: ["./pipimink"]

networks:
  pipimink-network:
    external: true
    name: pipimink-network